### ISSUE TITLE
How to build arm64, x86, x86_64

### ISSUE THREAD

**Issue by batkins2** [pmp-p/projects#2]
```
> Task :app:externalNativeBuildCleanDebug
This app only has 32-bit [armeabi-v7a] native libraries. Beginning August 1, 2019 Google Play store requires that all apps that include native libraries must provide 64-bit versions. For more information, visit https://g.co/64-bit-requirement
Clean rmipython armeabi-v7a
ninja: Entering directory '/home/osboxes/Desktop/Code/pydk/projects/org.beerware.empty/app/.cxx/cmake/debug/armeabi-v7a'
[1/1] Cleaning all built files...
Cleaning... 3 files.
```

I'm trying to run this on Anbox under Ubuntu 64-bit for testing and I'm getting:

```adb: failed to install ./app/build/outputs/apk/debug/app-debug.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]```

**Comment by pmp-p** [comment]
You can find that information in gradle documentation and gradle configuration files of the template.
https://github.com/pmp-p/pydk-android-gradle-template/blob/3.8p/%7B%7B%20cookiecutter.formal_name%20%7D%7D/app/build.gradle#L21
i won't be able to provide more help on gradle / android studio because i don't use them and don't plan to. Feel free to start your own template.

**Comment by batkins2** [comment]
```./app/build.gradle: line 21: abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'```
